title: Bayesian Election Modeling
logo: /assets/img/headshot.png
description: This site provides links to ongoing and past case studies. Feel free to send me an email under mnh2123 (at) columbia.edu for questions and comments.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
