title: Bayesian Election Modeling
logo: /assets/img/logo.png
description: This site provides links to ongoing and past case studies. Feel free to send me an email under mnh2123 (at) columbia.edu for questions and comments.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
